server:
  port: 8764
  ssl:
      enabled: true
      key-store: /opt/your-name.jks
      key-store-password: 19930308you
      key-store-type: JKS
      key-alias: 1
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  tomcat:
    max-connections: 5

spring:
  application:
    name: file
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.12.92.174:3306/arven?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: arvensong
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    check-template: false
    servlet:
      content-type: text/html

  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml


