eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 443
  ssl:
    enabled: true
    key-store: /opt/your-name.jks
    key-store-password: 19930308you
    key-store-type: JKS
    key-alias: 1

spring:
  application:
    name: zuul
#  resources:
#    chain:
#      strategy:
#        content:
#          enabled: true
#          paths: /**
#  mvc:
#    view:
#      prefix: /
#      suffix: .html

zuul:
  routes:
    client:
      path: /client/**
      serviceId: client
    baidu:
      path: /baidu/**
      url: http://www.baidu.com
    tally:
      path: /tally/**
      serviceId: tally
